# Generated by Django 5.2.5 on 2025-09-15 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_score_count_alter_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamwork_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
