# Generated by Django 5.2.5 on 2025-09-13 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_task_updated_at_remove_team_score_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='score_count',
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
