# Generated by Django 5.2.5 on 2025-09-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_team_teamwork_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='score_count',
            field=models.IntegerField(default=0),
        ),
    ]
